[project]
name = 'presale-stxcity-v1'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.presale1]
path = 'contracts/presale1.clar'
clarity_version = 3
epoch = 3.1

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 3
epoch = 3.1

[contracts.stxcity-token]
path = 'contracts/stxcity-token.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
